name: publish on mops

on:
  workflow_dispatch:
  push:
    tags:
      - moc-*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ZenVoich/setup-mops@3e94e453352269b34137b5ce49f09a8df81bed7d # v1.4.1
        with:
          # Make sure you set the MOPS_IDENTITY_PEM secret in your repository settings https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository
          identity-pem: ${{ secrets.MOPS_IDENTITY_PEM }}
      - run: mops install
      - run: mops publish
