name: Sync master and next-moc
on:
  push:
    branches:
      - master
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Merge master -> next-moc
        uses: devmasx/merge-branch@a1752b9ba42bb417ec19be7dc974e2faf77d3ef2 # v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: next-moc
          github_token: ${{ github.token }}
